
OBJS = tower_gen_thread_period_1ms.o \
       tower_user_thread_period_1ms.o \
       tower_gen_monitor_m1_1.o \
       tower_state_monitor_m1_1.o \
       tower_gen_monitor_m2_6.o \
       tower_state_monitor_m2_6.o

default: $(OBJS)

clean:
	-rm *.c *.h *.o

#Makefile                        tower_monitor_gen_m2_6.c
#ivory.h                         tower_monitor_gen_m2_6.h
#ivory_asserts.h                 tower_monitor_state_m1_1.c
#ivory_templates.h               tower_monitor_state_m1_1.h
#tower_gen_thread_period_1ms.c   tower_monitor_state_m2_6.c
#tower_gen_thread_period_1ms.h   tower_monitor_state_m2_6.h
#tower_monitor_gen_m1_1.c        tower_user_thread_period_1ms.c
#tower_monitor_gen_m1_1.h        tower_user_thread_period_1ms.h

