
OBJS = tower_gen_thread_period_1ms.o \
       tower_user_thread_period_1ms.o \
       tower_gen_thread_period_333us.o \
       tower_user_thread_period_333us.o \
       tower_gen_monitor_m1_1.o \
       tower_state_monitor_m1_1.o \
       tower_gen_monitor_m2_9.o \
       tower_state_monitor_m2_9.o \
       tower_init.o

default: $(OBJS)

clean:
	-rm *.o
veryclean:
	-rm *.c *.h *.o

