/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.1
 */
#ifndef __STM32_IVORY_INIT_H__
#define __STM32_IVORY_INIT_H__
#ifdef __cplusplus
extern "C" {
#endif
#include <ivory_hw_prim.h>
#include <stm32_init.h>
#include "ivory.h"
void Reset_Handler();

#ifdef __cplusplus
}
#endif
#endif /* __STM32_IVORY_INIT_H__ */