/* This file has been autogenerated by Ivory
 * Compiler version  0.1.0.1
 * and then modified a bunch by hand
 */
#include "timer_driver.h"
#include "ivory_hw_prim.h"
#include "ivory.h"

void timer_init()
{
    uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073887300U);
    
    /* reg modify 0x40023844: setBit rcc_apb2en_tim1 */
    ivory_hw_io_write_u32((uint32_t) 1073887300U, (uint32_t) (n_r0 |
                                                              (uint32_t) ((uint32_t) 1U <<
                                                                          (uint32_t) 0U)));
    
    uint32_t n_r1 = ivory_hw_io_read_u32((uint32_t) 1073807372U);
    
    /* reg modify 0x4001000c: setBit atim_dier_uie */
    ivory_hw_io_write_u32((uint32_t) 1073807372U, (uint32_t) (n_r1 |
                                                              (uint32_t) ((uint32_t) 1U <<
                                                                          (uint32_t) 0U)));
    /* reg set 0x40010028: setField atim_psc_psc */
    ivory_hw_io_write_u32((uint32_t) 1073807400U, (uint32_t) ((uint32_t) 167U <<
                                                              (uint32_t) 0U));
    /* reg set 0x4001002c: setField atim_16_data */
    ivory_hw_io_write_u32((uint32_t) 1073807404U,
                          (uint32_t) ((uint32_t) 65535U << (uint32_t) 0U));
    ASSERTS((bool) ((uint8_t) 12U < (uint8_t) ((uint8_t) 1U << (uint8_t) 4U)));
    ivory_hw_io_write_u8((uint32_t) 3758154777U, (uint8_t) ((uint8_t) 12U <<
                                                            (uint8_t) 4U));
    /* reg set 0xe000e100: setBit nvic_iser_setena.[25] */
    ivory_hw_io_write_u32((uint32_t) 3758153984U, (uint32_t) ((uint32_t) 1U <<
                                                              (uint32_t) 25U));
}

void timer_clear(const bool* n_var0)
{
    uint32_t n_r0 = ivory_hw_io_read_u32((uint32_t) 1073807376U);
    
    /* reg modify 0x40010010: clearBit atim_sr_uif */
    ivory_hw_io_write_u32((uint32_t) 1073807376U, (uint32_t) (n_r0 &
                                                              (uint32_t) ~(uint32_t) ((uint32_t) 1U <<
                                                                                      (uint32_t) 0U)));
}
