include ../stack.mk

test_simple:
	stack test tower-mini:simple --test-arguments '--src-dir=simple_codegen'

test_integrated:
	stack test tower-mini:integrated --test-arguments '--src-dir=integrated_codegen'
